## 数据源配置
executor:
  jdbc:
    url: jdbc:mysql://${db.host}:${db.port}/${db.name}?zeroDateTimeBehavior=convertToNull&useUnicode=yes&characterEncoding=UTF8&serverTimezone=GMT%2B8&useSSL=false
    username: ${db.user}
    password: ${db.pwd}
    driverClassName: com.mysql.cj.jdbc.Driver
    initialSize: 20
    maxActive: 50
    minIdle: 50
    maxWait: 30
    validationQuery: select 1
    testOnBorrow: false
    testOnReturn: false
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 25200000
    removeAbandoned: true
    removeAbandonedTimeout: 1800
    logAbandoned: true
    filters: mergeStat
    poolPreparedStatements: false

spring:
  profiles:
    active: test
  aop:
    # Set true to activate cglib, or it will use default jdk.
    proxy-target-class: true
    auto:

dubbo:
  application:
    name: lite-executor-provider
  registry:
    address: ${dubbo.registry.address}
    file: ${dubbo.registry.file}
  protocol:
    name: dubbo
    port: 20880
  qos:
    port: 22222

zk:
  servers: ${zk.servers}
  namespace: lite-flow-executor
#运行空间
lite:
  flow:
    executor:
      workspace: ${lite.flow.executor.workspace}
      isAutoRegisterToDB: true





