server:
  port: 8080
## 数据源配置
db:
  host: db.liteflow.cn
  port: 3306
  name: lite_flow
  user: lite
  pwd: lite

###redis配置
redis:
  host: redis.liteflow.cn
  port: 6379
  password:
  timeout: 100000
  pool:
    maxIdle: 20
    maxActive: 20
    maxWaitMillis: 1000
    testOnBorrow: true

logging:
    config: classpath:log4j2-test.xml

dubbo:
  registry:
    address: zookeeper://zk.liteflow.cn:2181
    cache: /tmp/dubbo.console.cache

zk:
  servers: zk.liteflow.cn:2181

